Fr 735
frontegg/frontegg-react pull request #111
Opened 2020-11-22 10:10 UTC by eldad-frontegg

2020-11-22 11:00 UTC, frontegg-david requested changes

2020-11-22 15:13 UTC, eldad-frontegg commented on packages/auth/src/SocialLogins/SocailLoginsSuccess.tsx
> +    return <div className={'fe-center'}><Loader/></div>
it doesn't work for me 
![image](https://user-images.githubusercontent.com/68379757/99907521-d786ca00-2ce5-11eb-9830-414bd9a4f056.png)

2020-11-22 15:48 UTC, frontegg-david commented on packages/auth/src/SocialLogins/SocailLoginsSuccess.tsx
> +    return <div className={'fe-center'}><Loader/></div>
okay leave it with fe-center i will check it latter

2020-11-23 14:20 UTC, frontegg-david approved these changes

2020-11-23 14:37 UTC, merged

2020-11-23 14:49 UTC, frontegg-david commented
/create-release