Add ng support
frontegg/frontegg-react pull request #15
Opened 2020-10-07 22:43 UTC by frontegg-david

2020-10-07 22:43 UTC, frontegg-david commented
/create release

2020-10-08 10:42 UTC, aviadmizrachi requested changes

2020-10-08 10:50 UTC, frontegg-david commented on packages/auth/src/components/authPageWrapper.tsx
> +  const header = props.header ?? <img src={props.headerImg ?? '//acmelogos.com/images/logo-1.svg'} alt='logo' />;
what about localhost with https?

2020-10-08 10:52 UTC, frontegg-david commented on packages/auth/src/components/authPageWrapper.tsx
> +  const header = props.header ?? <img src={props.headerImg ?? '//acmelogos.com/images/logo-1.svg'} alt='logo' />;
Tested it on localhost it's working

2020-10-08 11:05 UTC, aviadmizrachi approved these changes

2020-10-08 11:05 UTC, merged

2020-10-08 11:24 UTC, frontegg-david commented
/create release