Sso authorization step
frontegg/frontegg-react pull request #197
Opened 2020-12-24 16:33 UTC by MaxArnaut

Do not merge
Need to test

2020-12-26 17:48 UTC, eldad-frontegg commented
> Do not merge
> Need to test

Tested locally and fixed the API calls

2020-12-27 16:31 UTC, aviadmizrachi approved these changes

2020-12-27 16:35 UTC, merged

2020-12-27 16:39 UTC, frontegg-david requested changes

2020-12-27 16:39 UTC, frontegg-david commented on packages/auth/src/SSO/SSOManageAuthorizationPage/SSOManageAuthorizationPage.tsx
> +  const prefixT = 'auth.sso.authorization';
extract Title and Subtutle outside the SSOManageAuthPage component.

2020-12-27 16:39 UTC, frontegg-david commented on packages/rest-api/src/auth/index.ts
> + * @return array of providers configurations
fix comments and log message

2020-12-27 16:39 UTC, frontegg-david commented on packages/rest-api/src/auth/index.ts
> +  console.debug('getSocialLoginsProviders()');
do not copy & paste comments.