FR-789 feat(core): Added tab disabling for FeTabs component; disabled pwd tab in Profile
frontegg/frontegg-react pull request #279
Opened 2021-02-03 13:33 UTC by AntonReact

2021-02-03 13:35 UTC, AntonReact commented
https://user-images.githubusercontent.com/54889005/106754214-5d53b980-6635-11eb-9d1a-aa8c8b008221.mov

2021-02-04 10:43 UTC, frontegg-david commented
@AntonReact add support for material and semantic ui libraries

2021-02-06 15:18 UTC, frontegg-david commented
@AntonReact  ??

2021-02-07 11:27 UTC, frontegg-david requested changes

2021-02-07 11:27 UTC, frontegg-david commented on packages/auth/src/Profile/ProfileRouter.tsx
>    const [rootPath, isRootPathContext] = useRootPath(props, '/profile');
useAuthUser() instead of calling useAuth

2021-02-07 11:27 UTC, frontegg-david commented on packages/core/src/components/PageTabs/PageTabs.tsx
>  };
did you check for MaterialUI and Semantic libraries?

2021-02-07 11:27 UTC, frontegg-david commented on packages/core/src/components/PageTabs/PageTabs.tsx
> +
change this line to return items with {Component, disabled: boolean}

```
const items = useMemo(() => props.tabs.map(({ Title, disabled }) => ({Component, disabled}), [props.tabs]);
```

and remove the disabledTabs props. then change in the render function;

```
      {items.map(( { Component, disabled } , idx) => (
          <Tab
            className={classNames(`${clsPrefix}-item`, {
              [`${clsPrefix}-item-active`]: activeTab === idx,
            })}
            idx={idx}
            onClick={onTabChange}
            disabled={disabled}
            key={idx}
          >
              <Component />
          </Tab>
        ))}
```

2021-02-10 19:04 UTC, frontegg-david approved these changes

2021-02-10 19:05 UTC, merged