feat(auth): support render prop
frontegg/frontegg-react pull request #294
Opened 2021-02-16 10:26 UTC by pinikeizman

There are many use cases where we want to render Component even if authorization fails 
(e.g render a disable action button if the user has no permissions etc..).
This commit adds the ability to pass render function to `AuthorizedContent` component which in
turn pass the `isAuthorized` value to the render function. This way the
user can decide how to render the component depends on the value of `isAuthorized`.

2021-02-16 18:29 UTC, frontegg-david requested changes

2021-02-16 18:29 UTC, frontegg-david commented on packages/auth/src/AuthorizedContent/index.tsx
> +  render: (isAuthorized: boolean) => React.ReactNode | null;
Set this props as optional props.

```
  render?: (isAuthorized: boolean) => React.ReactNode
```

2021-02-17 07:38 UTC, pinikeizman commented on packages/auth/src/AuthorizedContent/index.tsx
> +  render: (isAuthorized: boolean) => React.ReactNode | null;
Good catch, miss that. Fixed.

2021-02-18 09:12 UTC, aviadmizrachi approved these changes

2021-02-18 09:12 UTC, aviadmizrachi approved these changes

2021-02-18 09:13 UTC, merged