feat: FR-1932 - added captcha for login/sign up; removed unused compo…
frontegg/frontegg-react pull request #302
Opened 2021-02-22 14:10 UTC by AntonReact

…nents demosaas

2021-02-22 14:18 UTC, serslon commented on packages/auth/src/components/ReCaptcha.tsx
> +  const state = useAuth(stateMapper);
Use here the `useField` hook and remove changes the value from the components to this component.
In this case, we can use the `useCallback` hook for setting a value to the formik.

2021-02-23 07:33 UTC, serslon approved these changes

2021-03-03 12:03 UTC, frontegg-david requested changes

2021-03-03 12:03 UTC, frontegg-david commented on packages/rest-api/src/auth/interfaces.ts
> +  recaptchaToken: string;
add it as optional

2021-03-03 12:03 UTC, frontegg-david commented on packages/rest-api/src/auth/interfaces.ts
> +export type ILogin = { email: string; password: string; recaptchaToken: string };
add recaptchaToken as optional

2021-03-03 12:03 UTC, frontegg-david commented
@AntonReact 
see request changes

2021-03-04 10:39 UTC, frontegg-david approved these changes

2021-03-04 10:39 UTC, merged