FR-11929 - Provide an external navigate method
frontegg/frontegg-react pull request #973
Opened 2023-05-28 07:11 UTC by rotemzif1

2023-05-29 11:19 UTC, frontegg-david requested changes

2023-05-29 11:19 UTC, frontegg-david commented on packages/react/src/FronteggProvider.tsx
> +  if (props.navigate) {
we already have some other hooks that uses the useHistory, I prefer to make custom provider that register out useHistory context and use it everywhere

2023-05-30 11:01 UTC, MaxArnautFrontegg approved these changes

2023-06-01 12:22 UTC, yuvalotem1 commented on packages/react/src/FronteggProvider.tsx
> +  const signUpUrl = app.store.getState().auth.routes.signUpUrl;
maybe we wrap it with the store and use `useAuthRoutes();` ?

2023-06-04 09:32 UTC, merged